### ISSUE TITLE
LINUX Version

### ISSUE THREAD

**Issue by hitam4450** [kingfisher63/avm_juischeck#1]
Hi, 

I am sure many users would love to run this application as native LINUX version!

Happy to see such a version, soon!

Best regards, hitam4450

**Comment by kingfisher63** [comment]
I am sure too... But this will not happen unless Microsoft makes the .NET Framework available on Linux.

**Comment by hitam4450** [comment]
Hi, have look here: 

https://www.mono-project.com/


regards, hitam4450

**Comment by kingfisher63** [comment]
Mono is only a partial implementation of the .NET Framework. Specifically it lacks WPF (Windows Presentation Foundation). JuisCheck requires WPF. So this is a 'cannot do'.

**Comment by hitam4450** [comment]
Thanks for your kind reply !
