### ISSUE TITLE
Auto close Pull request

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#12]
@kingfisher63 

What deos it mean

https://github.com/kingfisher63/avm_juischeck/blob/master/.github/lockdown.yml

Why your github system close automatic pull request without merge?

https://github.com/kingfisher63/avm_juischeck/tree/master/.github

**Comment by kingfisher63** [comment]
See https://github.com/apps/repo-lockdown

I have updated the documentation to reflect this.
