### ISSUE TITLE
Program didn't find new version on modem

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#13]
@kingfisher63 

I ran the application and it find a beta of 7,19 (inhaus).

After some times I  update the 7590 firmware to 7.20 official.

When I ran again the program it seems didn't detect new firmware evsrion and show info about previous inhause version and propose my the offciial 7.20 (that is already instaleldf).

I can fix it deleting the configuration and create a new configuration.ù

Did the program check reakl version instaleld in the mdoenm?

Thanks.

**Comment by kingfisher63** [comment]
JuisCheck sends a _BoxFirmwareUpdateCheck_ request to the AVM JUIS server using only the parameters configured in the device item. Specifically it does not first query any actual device specified in the _Device address_ field when doing an update check. The only time the _Device address_ field is used, is when you click the _Query_ button to copy data from the device into the device item.

AVM has apparently not configured 7.20 as an update for firmware _7.19-xxxxx Inhaus_ on their JUIS server. AFAIK they never do.
