### ISSUE TITLE
Firmware download link starting with "https://"

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#17]
@kingfisher63 

When you get the link to downlaod the firmware seems that it start with ex. 

"download.avm.de/inhaus/PSQ19P2NL/7490/FRITZ.Box_7490-07.24-87239-Inhaus.image"

If the link start with "http://" "or "downlaod.xxx" some browser in some configuration didn't download the firmware.

To fix these issues the link should start with "https://download.xxxxx" like

"https.//download.avm.de/inhaus/PSQ19P2NL/7490/FRITZ.Box_7490-07.24-87239-Inhaus.image"

Could you make this fix?

Thanks.

**Comment by kingfisher63** [comment]
JuisCheck 2.x has its own download engine using System.Net.WebClient. It appears that in .NET Framework 4.5 only SSLv3 and TLSv1.0 are enabled by default. The AVM download server supports neither (both protocols are deprecated) and aborts the TLS connection setup (protocol version alert). This is probably easy to fix.

**Comment by kingfisher63** [comment]
Fixed in v2.1.1

**Comment by bovirus** [comment]
Thanks a lot.
