### ISSUE TITLE
Downlaod link with https: instead http

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#18]
@kingfisher63

I tried but it seems that the problem is not completly fix.

If you use the link directly by your program it works like

http://download.avm.de/inhaus/PSQ19P2NL/7490/FRITZ.Box_7490-07.24-87373-Inhaus.image

but in some configuration with Google/Firefox if you posted the link if you clck the link the download didn't start.
If you make right click on link and select "Save as" it works.

Instead if you use https: like 

https://download.avm.de/inhaus/PSQ19P2NL/7490/FRITZ.Box_7490-07.24-87373-Inhaus.image

the click on link works.

Please take care that all official link for AVM labor start all with https.

**Comment by kingfisher63** [comment]
JuisCheck reports the link as retrieved from JUIS. Modifying that link would be a fundamentally flawed concept.
For the record: when I click either link in Firefox (v87.0), it will download the file. Your browser configuration may be broken.

**Comment by bovirus** [comment]
If the link that you exported by JIUS we have to post the link in teh forum with "https" to avoid the problem reprted.

**I'm so sorry but seems that my configuration is not broken and the problem is not my browser**

My browser works with all http downlaod link except AVM inhause firmware that start with http.

I checked that all official firmware links started all with https
