### ISSUE TITLE
Device homepage shortcut suggestion

### ISSUE THREAD

**Issue by grimson73** [kingfisher63/avm_juischeck#2]
Suggestion:
Right click (or button) for a device to go to homepage on configured IP Address.
Eg. click on device -> go to management page

**Comment by kingfisher63** [comment]
The purpose of JuisCheck is to provide a convenient interface for querying and downloading firmware updates. The suggestion is out of scope.

**Comment by grimson73** [comment]
Thanks for the informatieve reply!
