### ISSUE TITLE
FRITZ!Dect 500

### ISSUE THREAD

**Issue by fda77** [kingfisher63/avm_juischeck#3]
Für den 500 wird immer eine neuer Version angezeigt, da das Dateiformat nicht wie alle anderen Dect Geräte ist, zB
 - 34.10.16.16.005.avm.de.upd
 - 34.10.16.16.009.avm.de.upd
 - 34.10.16.16.011.avm.de.upd

HW 10.(0)1
FW 16.16

**Comment by kingfisher63** [comment]
This is on my list for the next update. I just need to find some time to implement it.

**Comment by kingfisher63** [comment]
JuisCheck now uses the last two number parts of the filename to determine the version. So 34.10.16.16.011.avm.de.upd will be shown as 16.011.
