### ISSUE TITLE
Add new languauge to JuisCheck

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#4]
@kingfisher63

Is there any option translating/adding a new file for

JuisCheck/lang/JCStrings.res

to have additional language (like Italian) for the application?

**Comment by kingfisher63** [comment]
Yes. The next release will have the Italian localization that you kindly sent me.

**Comment by kingfisher63** [comment]
@bovirus: The next release will have a few new strings. I will contact you before release to have them translated.
