### ISSUE TITLE
Program enanhcement

### ISSUE THREAD

**Issue by bovirus** [kingfisher63/avm_juischeck#5]
I have some proposal/requuest for program enhancement

**_- Change the source code to enable multi-.language GUI_**
I already tried to add Juischeck\Lang\JCString.it.resx (add Italian language) and compile source code but the interface is always in English.
Probably the source code needs some changes to enable multi-language MUI.

**_- Exit without saving with Yes/No/Cancelnot included in language files_**
I translated the progranm in Italian translating all strings in JCString.resx file.
Then I compiled the source and I got the program with Italian interface,.
I found an issue about untranslated strings for button Yes/No/Cancel if you made some settings and exit without saving it.
It seems that these button text strings are not included in language file.

**_- Default folder for configuration files_**
Currently default folder for configuration files (list of devices) is "Documents" folder.
I propose you to change to the current folder (folder where you run Juischeck.exe):
For me it's usefull for portable use.
 
**_- Automatically load configuration file_**

I propose to change the code adding the option to check automatically the availability of a default configuration file (ex default.xml).
If the program found default configuration file in current folder (folder where you run Juischeck.ece) the program load it automatically.

**Comment by kingfisher63** [comment]
I have created separate issues for each feature. Kindly create separate issues in the future for unrelated requests.
